; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Mar 01 2020 06:50:44 GMT+0100 (Środkowoeuropejski czas stand.)
; ================================================================================

DATAIHNO8BJTY4B:
	dc.w DATAIHNO8BJTY4B_0-DATAIHNO8BJTY4B, DATAIHNO8BJTY4B_1-DATAIHNO8BJTY4B
	dc.w DATAIHNO8BJTY4B_2-DATAIHNO8BJTY4B, DATAIHNO8BJTY4B_3-DATAIHNO8BJTY4B
	dc.w DATAIHNO8BJTY4B_4-DATAIHNO8BJTY4B, DATAIHNO8BJTY4B_5-DATAIHNO8BJTY4B
	dc.w DATAIHNO8BJTY4B_6-DATAIHNO8BJTY4B
DATAIHNO8BJTY4B_0: dc.b $1
	dc.b $F3, $F, $0, $0, $F4
DATAIHNO8BJTY4B_1: dc.b $1
	dc.b $F4, $F, $0, $10, $F0
DATAIHNO8BJTY4B_2: dc.b $1
	dc.b $F4, $F, $0, $30, $F4
DATAIHNO8BJTY4B_3: dc.b $1
	dc.b $F4, $F, $0, $30, $F4
DATAIHNO8BJTY4B_4: dc.b $1
	dc.b $F4, $F, $0, $30, $F0
DATAIHNO8BJTY4B_5: dc.b $2
	dc.b $F4, $6, $0, $4B, $E8
	dc.b $F4, $A, $0, $51, $F8
DATAIHNO8BJTY4B_6: dc.b $1
	dc.b $F3, $F, $0, $51, $F0
	even