; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Mar 06 2020 07:05:01 GMT+0100 (Środkowoeuropejski czas stand.)
; ================================================================================

DATAVBTDPBUACOQ:
	dc.w DATAVBTDPBUACOQ_0-DATAVBTDPBUACOQ
DATAVBTDPBUACOQ_0: dc.b $2
	dc.b $F0, $B, $0, $0, $E8
	dc.b $F0, $B, $0, $C, $0
	even