; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Feb 06 2020 02:37:16 GMT+0100 (Środkowoeuropejski czas stand.)
; ================================================================================

DATAEMFU8B9YX5N:
	dc.w $0, DATAEMFU8B9YX5N_1-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_2-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_3-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_4-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_5-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_6-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_7-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_8-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_9-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_A-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_B-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_C-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_D-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_E-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_F-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_10-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_11-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_12-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_13-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_14-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_15-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_16-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_17-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_18-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_19-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_1A-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_1B-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_1C-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_1D-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_1E-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_1F-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_20-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_21-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_22-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_23-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_24-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_25-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_26-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_27-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_28-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_29-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_2A-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_2B-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_2C-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_2D-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_2E-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_2F-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_30-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_31-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_32-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_33-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_34-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_35-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_36-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_37-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_38-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_39-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_3A-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_3B-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_3C-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_3D-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_3E-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_3F-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_40-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_41-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_42-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_43-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_44-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_45-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_46-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_47-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_48-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_49-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_4A-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_4B-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_4C-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_4D-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_4E-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_4F-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_50-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_51-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_52-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_53-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_54-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_55-DATAEMFU8B9YX5N
	dc.w DATAEMFU8B9YX5N_56-DATAEMFU8B9YX5N, DATAEMFU8B9YX5N_57-DATAEMFU8B9YX5N
DATAEMFU8B9YX5N_1: dc.b $4
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
DATAEMFU8B9YX5N_2: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATAEMFU8B9YX5N_3: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATAEMFU8B9YX5N_4: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATAEMFU8B9YX5N_5: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F0
	dc.b $C, $8, $0, $C, $F8
DATAEMFU8B9YX5N_6: dc.b $4
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $9, $0, $8, $EC
	dc.b $FB, $6, $0, $E, $4
	dc.b $B, $4, $0, $14, $EC
DATAEMFU8B9YX5N_7: dc.b $2
	dc.b $EC, $D, $0, $0, $ED
	dc.b $FC, $E, $0, $8, $F5
DATAEMFU8B9YX5N_8: dc.b $2
	dc.b $ED, $9, $0, $0, $F3
	dc.b $FD, $A, $0, $6, $F3
DATAEMFU8B9YX5N_9: dc.b $4
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $9, $0, $6, $EC
	dc.b $FB, $6, $0, $C, $4
	dc.b $B, $4, $0, $12, $EC
DATAEMFU8B9YX5N_A: dc.b $2
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $EB
DATAEMFU8B9YX5N_B: dc.b $3
	dc.b $ED, $D, $0, $0, $EC
	dc.b $FD, $C, $0, $8, $F4
	dc.b $5, $9, $0, $C, $F4
DATAEMFU8B9YX5N_C: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $6, $0, $6, $3
	dc.b $FB, $8, $0, $C, $EB
	dc.b $3, $9, $0, $F, $F3
	dc.b $13, $0, $0, $15, $FB
DATAEMFU8B9YX5N_D: dc.b $6
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $C, $0, $8, $EC
	dc.b $4, $9, $0, $C, $F4
	dc.b $FC, $5, $0, $12, $C
	dc.b $F4, $0, $0, $16, $14
DATAEMFU8B9YX5N_E: dc.b $4
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $D, $0, $8, $F5
	dc.b $D, $8, $0, $10, $FD
DATAEMFU8B9YX5N_F: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $5, $0, $6, $3
	dc.b $FB, $D, $0, $A, $F3
	dc.b $B, $8, $0, $12, $F3
	dc.b $13, $4, $0, $15, $FB
DATAEMFU8B9YX5N_10: dc.b $4
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $D, $0, $8, $F4
	dc.b $C, $8, $0, $10, $FC
DATAEMFU8B9YX5N_11: dc.b $5
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $0, $0, $8, $ED
	dc.b $FD, $D, $0, $9, $F5
	dc.b $D, $8, $0, $11, $FD
DATAEMFU8B9YX5N_12: dc.b $4
	dc.b $F4, $7, $0, $0, $EB
	dc.b $EC, $9, $0, $8, $FB
	dc.b $FC, $4, $0, $E, $FB
	dc.b $4, $9, $0, $10, $FB
DATAEMFU8B9YX5N_13: dc.b $2
	dc.b $F4, $7, $0, $0, $EC
	dc.b $EC, $B, $0, $8, $FC
DATAEMFU8B9YX5N_14: dc.b $2
	dc.b $F4, $6, $0, $0, $ED
	dc.b $F4, $A, $0, $6, $FD
DATAEMFU8B9YX5N_15: dc.b $4
	dc.b $F4, $6, $0, $0, $EB
	dc.b $EC, $9, $0, $6, $FB
	dc.b $FC, $4, $0, $C, $FB
	dc.b $4, $9, $0, $E, $FB
DATAEMFU8B9YX5N_16: dc.b $2
	dc.b $F4, $6, $0, $0, $EC
	dc.b $F4, $B, $0, $6, $FC
DATAEMFU8B9YX5N_17: dc.b $3
	dc.b $F4, $7, $0, $0, $ED
	dc.b $EC, $0, $0, $8, $FD
	dc.b $F4, $A, $0, $9, $FD
DATAEMFU8B9YX5N_18: dc.b $6
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $4, $0, $6, $F3
	dc.b $F5, $4, $0, $8, $EB
	dc.b $F5, $A, $0, $A, $FB
	dc.b $D, $0, $0, $13, $FB
	dc.b $FD, $0, $0, $14, $13
DATAEMFU8B9YX5N_19: dc.b $6
	dc.b $FC, $6, $0, $0, $EC
	dc.b $E4, $8, $0, $6, $F4
	dc.b $EC, $4, $0, $9, $FC
	dc.b $F4, $4, $0, $B, $EC
	dc.b $F4, $A, $0, $D, $FC
	dc.b $C, $0, $0, $16, $FC
DATAEMFU8B9YX5N_1A: dc.b $4
	dc.b $FB, $6, $0, $0, $ED
	dc.b $F3, $4, $0, $6, $ED
	dc.b $EB, $A, $0, $8, $FD
	dc.b $3, $4, $0, $11, $FD
DATAEMFU8B9YX5N_1B: dc.b $5
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $8, $0, $6, $F3
	dc.b $F5, $4, $0, $9, $EB
	dc.b $F5, $D, $0, $B, $FB
	dc.b $5, $8, $0, $13, $FB
DATAEMFU8B9YX5N_1C: dc.b $4
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
DATAEMFU8B9YX5N_1D: dc.b $5
	dc.b $FB, $6, $0, $0, $ED
	dc.b $EB, $A, $0, $6, $FD
	dc.b $F3, $4, $0, $F, $ED
	dc.b $3, $4, $0, $11, $FD
	dc.b $B, $0, $0, $13, $FD
DATAEMFU8B9YX5N_1E: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAEMFU8B9YX5N_1F: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAEMFU8B9YX5N_20: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAEMFU8B9YX5N_21: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAEMFU8B9YX5N_22: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATAEMFU8B9YX5N_23: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATAEMFU8B9YX5N_24: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATAEMFU8B9YX5N_25: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATAEMFU8B9YX5N_26: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAEMFU8B9YX5N_27: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAEMFU8B9YX5N_28: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAEMFU8B9YX5N_29: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAEMFU8B9YX5N_2A: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATAEMFU8B9YX5N_2B: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATAEMFU8B9YX5N_2C: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATAEMFU8B9YX5N_2D: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATAEMFU8B9YX5N_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAEMFU8B9YX5N_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAEMFU8B9YX5N_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAEMFU8B9YX5N_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAEMFU8B9YX5N_32: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAEMFU8B9YX5N_33: dc.b $2
	dc.b $F4, $E, $0, $0, $EC
	dc.b $F4, $2, $0, $C, $C
DATAEMFU8B9YX5N_34: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAEMFU8B9YX5N_35: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAEMFU8B9YX5N_36: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAEMFU8B9YX5N_37: dc.b $2
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $E, $0, $6, $F0
DATAEMFU8B9YX5N_38: dc.b $4
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $D, $0, $6, $F0
	dc.b $D, $4, $0, $E, $0
	dc.b $5, $0, $0, $10, $E8
DATAEMFU8B9YX5N_39: dc.b $4
	dc.b $F4, $4, $0, $0, $FC
	dc.b $FC, $D, $0, $2, $F4
	dc.b $C, $8, $0, $A, $F4
	dc.b $4, $0, $0, $D, $EC
DATAEMFU8B9YX5N_3A: dc.b $3
	dc.b $EC, $8, $8, $0, $E8
	dc.b $F4, $2, $8, $3, $0
	dc.b $F4, $F, $8, $6, $E0
DATAEMFU8B9YX5N_3B: dc.b $3
	dc.b $EC, $E, $8, $0, $E8
	dc.b $4, $D, $8, $C, $E0
	dc.b $C, $0, $18, $14, $0
DATAEMFU8B9YX5N_3C: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATAEMFU8B9YX5N_3D: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
DATAEMFU8B9YX5N_3E: dc.b $3
	dc.b $F4, $D, $0, $0, $E4
	dc.b $FC, $0, $0, $8, $4
	dc.b $4, $C, $0, $9, $EC
DATAEMFU8B9YX5N_3F: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATAEMFU8B9YX5N_40: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $4, $0, $C, $F8
	dc.b $10, $0, $0, $E, $F8
DATAEMFU8B9YX5N_41: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATAEMFU8B9YX5N_42: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATAEMFU8B9YX5N_43: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $F0, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATAEMFU8B9YX5N_44: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATAEMFU8B9YX5N_45: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATAEMFU8B9YX5N_46: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATAEMFU8B9YX5N_47: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATAEMFU8B9YX5N_48: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATAEMFU8B9YX5N_49: dc.b $2
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $E, $0, $6, $F0
DATAEMFU8B9YX5N_4A: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $5, $0, $9, $F8
	dc.b $E4, $0, $0, $D, $F8
DATAEMFU8B9YX5N_4B: dc.b $3
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $B, $0, $A, $F4
DATAEMFU8B9YX5N_4C: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATAEMFU8B9YX5N_4D: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATAEMFU8B9YX5N_4E: dc.b $2
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $F, $0, $3, $F0
DATAEMFU8B9YX5N_4F: dc.b $3
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $E, $0, $3, $F0
	dc.b $C, $8, $0, $F, $F8
DATAEMFU8B9YX5N_50: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAEMFU8B9YX5N_51: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
DATAEMFU8B9YX5N_52: dc.b $1
	dc.b $F8, $1, $0, $0, $FC
DATAEMFU8B9YX5N_53: dc.b $3
	dc.b $F4, $D, $8, $0, $E4
	dc.b $FC, $5, $8, $8, $4
	dc.b $4, $8, $8, $C, $EC
DATAEMFU8B9YX5N_54: dc.b $3
	dc.b $F4, $D, $8, $0, $FC
	dc.b $FC, $0, $8, $8, $F4
	dc.b $4, $C, $8, $9, $F4
DATAEMFU8B9YX5N_55: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $8, $C, $0, $E, $F4
DATAEMFU8B9YX5N_56: dc.b $3
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $E, $0, $6, $EC
	dc.b $3, $1, $0, $12, $C
DATAEMFU8B9YX5N_57: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F8, $2, $0, $10, $C
	even